// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package models

import "encoding/json"
import "fmt"
import "reflect"
import "time"

// A book tracked in Marginalia.
type Book struct {
	// Author of the book.
	Author string `json:"author"`

	// RFC 3339 timestamp in UTC of when the book was added. The frontend converts
	// this to UTC+1 for display, per AGENTS.md section 13.
	DateAdded time.Time `json:"dateAdded"`

	// Unique identifier of the book.
	ID string `json:"id"`

	// Labels attached to the book. Optional, defaults to an empty list.
	Labels []Label `json:"labels,omitempty,omitzero"`

	// Free-form notes about the book. Optional.
	Notes *string `json:"notes,omitempty,omitzero"`

	// Status corresponds to the JSON schema field "status".
	Status Status `json:"status"`

	// Title of the book.
	Title string `json:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Book) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["author"]; raw != nil && !ok {
		return fmt.Errorf("field author in Book: required")
	}
	if _, ok := raw["dateAdded"]; raw != nil && !ok {
		return fmt.Errorf("field dateAdded in Book: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Book: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in Book: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in Book: required")
	}
	type Plain Book
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Book(plain)
	return nil
}

// A tag that can be attached to a book.
type Label struct {
	// Hex color code used to render the label, e.g. "#FF5733".
	Color string `json:"color"`

	// Unique identifier of the label.
	ID string `json:"id"`

	// Display name of the label.
	Name string `json:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Label) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["color"]; raw != nil && !ok {
		return fmt.Errorf("field color in Label: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Label: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Label: required")
	}
	type Plain Label
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Label(plain)
	return nil
}

type Status string

const StatusFinished Status = "finished"
const StatusQuit Status = "quit"
const StatusReading Status = "reading"
const StatusWillRead Status = "will-read"

var enumValues_Status = []interface{}{
	"will-read",
	"reading",
	"finished",
	"quit",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Status) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Status {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Status, v)
	}
	*j = Status(v)
	return nil
}
